/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.redpillanalytics.bigquery.load

import org.apache.spark.*

class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        println new App().greeting
    }

    def getFrame() {

    }
}
